version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /fastq-dump  # absolute path
    testParameterFiles: ""  # absolute path
    readMePath: "" # absolute path
    authors:
      - name: Hyunmin Kim 
        email: human.gim@gmail.com
          
