name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - { path: "./fastq-dump/Dockerfile", tag: "twokims/fastq-dump:latest" }
          - { path: "./cnmf-x/Dockerfile", tag: "twokims/cnmf-x:latest" }
          - { path: "./infercnv/Dockerfile", tag: "twokims/cnmf-x:latest" }

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images in a matrix
      - name: Build and push Docker image
        env:
          GITHUB_REPO_URL: ${{ github.repository }}
          REPO_TOKEN : ${{ secrets.REPO_TOKEN }}
        run: |
          docker build --build-arg GITHUB_REPO_URL=${GITHUB_REPO_URL} \
                       --build-arg REPO_TOKEN=${REPO_TOKEN} \
                       -t ${{ matrix.dockerfile.tag }} \
                       -f ${{ matrix.dockerfile.path }} .
          docker push ${{ matrix.dockerfile.tag }}
